### ISSUE TITLE
Could it replace calls to global $wp_query?

### ISSUE THREAD

**Issue by kapooostin** [Giuseppe-Mazzapica/Amygdala#2]
I'm trying to wrap my head around Amygdala. 
I use it inside a class that is called when a specific template is rendered:

``` php
// this works
$global $wp_query;
$vars = $wp_query->query_vars;

// this returns FALSE
$request = new \Brain\Request;
$vars = $request->get( 'query' );
```

Or am I missing anything?

**Comment by gmazzap** [comment]
Amygdala is just a wrapper to avoid calls to superglobals like `$_GET`, `$_POST` and so on that also perform some filtering via `filter_var` to the retrieved values.

``` php
$request = new \Brain\Request;
$vars = $request->get( 'query' );
```

has nothing to do with `global $query`. "query" is the key used to store `$_GET`, and tou get `FALSE` because you're not using any filter.

In short, no,  `Amygdala` is not used to wrap `$GLOBALS` and you can't use it to retrieve values from there.

**Comment by kapooostin** [comment]
OK, I see. Thank you!
